version: "3.9"

services:
  fastapi:
    build:
      context: .
      dockerfile: Fastapi.dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
